### ISSUE TITLE
compilation error vector.hpp

### ISSUE THREAD

**Issue by adevress** [Eyescale/vmmlib#44]
Brion does not compile with GCC 4.9.4  due to a missing header on vmmlib.

The Vector template in vmmlib/vector.hpp  use std::runtime_error without including  explicitely stdexcept

```
[  7%] Building CXX object vmmlib/tests/CMakeFiles/matrix.dir/matrix.cpp.o
In file included from /tmp/nix-build-brion-1.6.0-DEV.drv-0/Brion-f936a45/vmmlib/vmmlib/aabb.hpp:35:0,
                 from /tmp/nix-build-brion-1.6.0-DEV.drv-0/Brion-f936a45/vmmlib/tests/aabb.cpp:29:
/tmp/nix-build-brion-1.6.0-DEV.drv-0/Brion-f936a45/vmmlib/vmmlib/vector.hpp: In member function 'T& vmml::vector<M, T>::at(size_t)':
/tmp/nix-build-brion-1.6.0-DEV.drv-0/Brion-f936a45/vmmlib/vmmlib/vector.hpp:612:15: error: 'runtime_error' is not a member of 'std'
         throw std::runtime_error( "at() - index out of bounds" );
               ^
/tmp/nix-build-brion-1.6.0-DEV.drv-0/Brion-f936a45/vmmlib/vmmlib/vector.hpp: In member function 'const T& vmml::vector<M, T>::at(size_t) const':
/tmp/nix-build-brion-1.6.0-DEV.drv-0/Brion-f936a45/vmmlib/vmmlib/vector.hpp:621:15: error: 'runtime_error' is not a member of 'std'
         throw std::runtime_error( "at() - index out of bounds" );
               ^
In file included from /tmp/nix-build-brion-1.6.0-DEV.drv-0/Brion-f936a45/vmmlib/vmmlib/quaternion.hpp:39:0,
                 from /tmp/nix-build-brion-1.6.0-DEV.drv-0/Brion-f936a45/vmmlib/tests/quaternion.cpp:29:
/tmp/nix-build-brion-1.6.0-DEV.drv-0/Brion-f936a45/vmmlib/vmmlib/vector.hpp: In member function 'T& vmml::vector<M, T>::at(size_t)':
/tmp/nix-build-brion-1.6.0-DEV.drv-0/Brion-f936a45/vmmlib/vmmlib/vector.hpp:612:15: error: 'runtime_error' is not a member of 'std'
         throw std::runtime_error( "at() - index out of bounds" );
               ^
/tmp/nix-build-brion-1.6.0-DEV.drv-0/Brion-f936a45/vmmlib/vmmlib/vector.hpp: In member function 'const T& vmml::vector<M, T>::at(size_t) const':
/tmp/nix-build-brion-1.6.0-DEV.drv-0/Brion-f936a45/vmmlib/vmmlib/vector.hpp:621:15: error: 'runtime_error' is not a member of 'std'
         throw std::runtime_error( "at() - index out of bounds" );
```
               ^

**Comment by eile** [comment]
For non-supported compilers please submit a PR. We can't test and fix all OS/compiler combinations. Since you use it, it's much easier to fix for you than for us.

**Comment by adevress** [comment]
You should normally have the problem with any compiler 4.9 >

**Comment by eile** [comment]
Probably, production compiler is 4.8.x though. Afaik we don't even have a 4.9 module yet (and no nix in production)

**Comment by adevress** [comment]
Does not matter, I sent you the pull request. It's a trivial fix
